repos:
- hooks:
  - id: trailing-whitespace
    exclude: ^inputs/.*\.txt$
  - id: end-of-file-fixer
    exclude: ^inputs/.*\.txt$
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0

- hooks:
  - args:
    - --autofix
    files: \.kt$
    exclude: ^\.idea/fileTemplates/.*\.kt$
    id: pretty-format-kotlin
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0

- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.0.0
